### ISSUE TITLE
rootfs_providers

### ISSUE THREAD

**Issue by datianshi** [cloudfoundry-incubator/diego-windows-msi#4]
I am trying to install diego windows cell

but once I got installed

curl http://receptor.10.65.233.228.xip.io/v1/cells

[{"cell_id":"WIN-BJA20KMFAGR","zone":"z1","capacity":{"memory_mb":8191,"disk_mb":40607,"containers":256},"rootfs_providers":null}

I got rootfs_providers as null

diego 1353 and cf 213

**Comment by jvshahid** [comment]
@datianshi did you enable windows support in diego and how did you deploy diego ? Also what happens when you try to push a windows app ?

**Comment by jvshahid** [comment]
Talked to @datianshi over slack, turns out the versions of the msi and diego he is using aren't compatible. closing this issue.
