### ISSUE TITLE
garden-windows tests fail with "no gcc found in path"

### ISSUE THREAD

**Issue by prysmakou** [cloudfoundry-incubator/diego-windows-msi#6]
When run make.bat it fails on "lifecycle_suite_test" of garden-windows.
![image](https://cloud.githubusercontent.com/assets/2300459/10011475/f244a3d8-60fa-11e5-9408-7b52e0829613.png)

**Comment by benmoss** [comment]
Not sure what would be causing this, but it seems like it's an issue with your Go compiler. How did you install Go? We are using Go 1.4.2 with the MSI installer.

**Comment by prysmakou** [comment]
I use [Go1.5.1](https://golang.org/dl/). Do I need to use 1.4.2? If so, could you please add this requirement to Readme file?

**Comment by benmoss** [comment]
Yep, we mention it in https://github.com/cloudfoundry-incubator/diego-windows-msi/blob/master/docs/BUILDING.md but I added a note to Garden-Windows' README as well.
